org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
org.gradle.java.home=C\:\\Program Files\\Eclipse Adoptium\\jdk-21.0.12.101-hotspot
# Fix: suppress ANDROID_PREFS_ROOT vs ANDROID_USER_HOME conflict
android.prefs.root=C:\\Users\\cheth\\.android
